sudo: required

services:
  - docker

language: node_js
node_js:
  - 8

branches:
  only:
    - master

cache:
  yarn: true

env:
  global:
    # Codecov token
    - secure: 'M5is9i1qEyS07aLK89ewDsnGmLG5+zTkZWVq4TPp6FHIfwBVwI9x+OKMxczeAgl2WO1nfcpto/RwibqRZT0xC/CCPY5swhbXExM4deS+3397AGPWhz5rJHUhRHLfhJkOajg8/UmBkyYCJnXMgMYbs3F1+JMHt13ijMzc74gPJJz5p2Yu5/PtsNEjQ9mjEcTefwQc56MhE+rrsKX1LIdE+BxoHdxjaCf2SJJy85TRoN6YAiKh2pT2VhA6qM+ntrwt1ICErbNtH+vECVtho1Xq8orODujfO3ZHlqsi0Y/Q9Z1shyGSPX/A7m5Vd0l8XdfpeDCkHcvPUoEckVYiRAKC1BjQqQ8Np/rrNDzA4XU7odDTbEzrQGfDIPRpEaYKNOHkL7VgF06ps/UFDdtSoGnEN+Cr+HFRQy2/lAqAqjC8cxsWQir+b3ZPzsfqBJhCanauZrUYk1KQ9HcWiBcywIRzshfJ45ZKGqcjjL6B4HgeNMygPTBhDC4rdYsPg9CJ+zaWGpl57fnemCrdvSQuSmldm6cJkDpNXLqM99MzhesiPqjwaKAp2GEcizaQZf5dWz+YmXHWRbcYvPfofUn6On53+pXtnzPp2Y5jRSKZvalZLKPv1P3A0xSXQYvzF5AyEyhqZBo2OCzgk7kZT3z89Of9540dqLdthN7FQTXqeN5grOU='

jobs:
  include:
    - stage: Unit tests
      script:
        - yarn ci-validate
        - codecov
    - stage: Integration tests
      script:
        - ./run-integration-test.sh
    - stage: npm release
      node_js: 8
      if: tag IS present
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: 'dev@leadformance.com'
        api_key:
          secure: 'YZse9VhBv+Is2BhpcVA58/wBBmVqbzP5LyRvR8nLknwO0T1NUaQ44i2mXieHVRSomiV091aTCTcLICy6MSSyzmnLevMm8dg6cad/ns8/kw4Uj4ods1XZrKraUt5sXe6T9kMu+ofpRpBUonelfsqxq3J+FyA3D7bbTUBr3fhC6pO0g1QcLuepUXAFQTh060stHWhe620aWOWy1A2AIJ3kS8Hg7svWlPQOr7MAkHdqIGnovZe00tPygOgwGUw6PtI1+dZb9VXrzieC0BqDOIAZh5oLSm1jCM7dRCr8ENm7lTUSuLKhil2WDZfSLlXLbwWh6Jb2812sTmhM4tfTuM7WzBGosI8fXRLHzZmG3iCmJPJB3HKCzIwQAW5FiGmqMPuy/TFR0SOJhbIUDx2JEjkeciX8RcBTvW4yrReH3X0yXv+bW3KyocRJ/DE1+Bvo+q6oPq4Vq8SaaeanRsBNmQRsU3ZXUCjrkuN/LtEYx50geeh0AO4DApdiR8zB9EkNrtdVcL0UpZKNYw5qh1QJfzKQ089w1MLbwHulq5GjE5aGWbseynbEOKmCv906/i59uqzaoCDgyjKoIBlupcbTahZSl0X0oolWRLwH7QynGodID7oUzm7ceLZyhK3zpVIOTOP/dKXm1Qe5seHFUJJoZTr8JWm9ATaS07zxDXtM3pca0lA='
        on:
          tags: true
        skip_cleanup: true
