sudo: required

services:
  - docker

language: node_js
node_js:
  - 8

branches:
  only:
    - master

cache:
  yarn: true

env:
  global:
    - CODECOV_TOKEN="ea6016cb-b8d7-4f33-8faf-9e438d3e5cde"

jobs:
  include:
    - stage: Unit tests
      script:
        - yarn ci-validate
        - codecov
    - stage: Integration tests
      script:
        - ./run-integration-test.sh
