module.exports = {
  path: '/v1/jobs',
  template: {
    name: (params, query, body) => body.name,
    schedule: (params, query, body) => body.schedule,
    executor: (params, query, body) => body.executor,
    executor_config: (params, query, body) => body.executor_config,
    timezone: '',
    shell: false,
    command: '',
    environment_variables: null,
    owner: '',
    owner_email: '',
    success_count: 0,
    error_count: 0,
    last_success: '0001-01-01T00:00:00Z',
    last_error: '0001-01-01T00:00:00Z',
    disabled: false,
    tags: null,
    retries: 0,
    dependent_jobs: null,
    parent_job: '',
    processors: null,
    concurrency: 'allow',
    status: '',
  },
};
